# Generated by Django 5.0.6 on 2024-06-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoadInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('size', models.CharField(max_length=100)),
                ('pickup_location', models.CharField(max_length=200)),
                ('drop_location', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('mobile_number', models.CharField(max_length=15)),
                ('time_of_pickup', models.TimeField()),
            ],
        ),
    ]
